"use client";
import {companyFetch} from "@/app/company-fetch";import {todayIST} from "@/app/lib/date";import {FormEvent,useState} from "react";import {Download,LockKeyhole,ShieldCheck} from "lucide-react";
type Lock={id:string;periodStart:string;periodEnd:string;reason:string};type Member={id:string;email:string;role:string;status:string};type Mode="review"|"lock"|"member";
export default function ControlPanel({locks,members}:{locks:Lock[];members:Member[]}){
 const[mode,setMode]=useState<Mode>("review"),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");setError("");const f=new FormData(e.currentTarget);const payload=mode==="member"?{action:"member",email:f.get("email"),role:f.get("role")}:{action:mode,periodStart:f.get("periodStart"),periodEnd:f.get("periodEnd"),...(mode==="lock"?{reason:f.get("reason")}:{})};const response=await companyFetch("/api/accounts/controls",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();setBusy(false);if(!response.ok){setError(body.message||"Could not save.");return}setMsg(mode==="review"?`${body.reviewed||0} entries marked reviewed.`:mode==="lock"?"Period locked.":"Team access saved.");setTimeout(()=>location.reload(),800)}
 async function backup(){setBusy(true);setError("");setMsg("");try{const response=await companyFetch("/api/accounts/controls");if(!response.ok)throw Error("Company data could not be exported.");const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`commons-backup-${todayIST()}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMsg("Verified-checksum backup downloaded. Use Restore Backup to validate it.");}catch(err){setError(err instanceof Error?err.message:"Export failed.");}finally{setBusy(false)}}
 return <><div className="control-overview"><article><ShieldCheck/><strong>Review before close</strong><small>Every period needs a named reviewer</small></article><article><LockKeyhole/><strong>{locks.length} locked periods</strong><small>Closed dates cannot receive entries</small></article><article><Download/><strong>Portable backup</strong><small>Company records and Tally history; excludes credentials</small><button type="button" onClick={backup} disabled={busy}>Download now</button><a href="/accounts/restore">Verify or restore →</a></article></div><section className="inline-workspace"><div className="mode-tabs"><button type="button" className={mode==="review"?"active":""} onClick={()=>setMode("review")}>Review entries</button><button type="button" className={mode==="lock"?"active":""} onClick={()=>setMode("lock")}>Lock period</button><button type="button" className={mode==="member"?"active":""} onClick={()=>setMode("member")}>Team access</button></div><form className="plain-book-form compact" onSubmit={submit}>{mode==="member"?<div className="form-grid"><label><span>Team member email</span><input name="email" type="email" required/></label><label><span>Access level</span><select name="role" defaultValue="accountant"><option value="viewer">View only</option><option value="operator">Record daily work</option><option value="accountant">Review and close books</option><option value="owner">Full control</option></select></label></div>:<><div className="form-grid"><label><span>From</span><input name="periodStart" type="date" required/></label><label><span>To</span><input name="periodEnd" type="date" required/></label>{mode==="lock"&&<label className="full-field"><span>Reason</span><input name="reason" placeholder="Example: August books approved" required/></label>}</div><p className="control-warning">{mode==="review"?"Confirm that bills, receipts, purchases, payroll, bank and GST records for this range have been checked.":"Commons allows locking only after every entry in the period is reviewed."}</p></>}{error&&<p className="form-error">{error}</p>}{msg&&<p className="form-success">{msg}</p>}<button className="submit-button" disabled={busy}>{busy?"Saving…":mode==="review"?"Confirm review":"Save"}</button></form>{locks.length>0&&<div className="saved-controls"><h3>Locked periods</h3>{locks.map(lock=><p key={lock.id}><b>{lock.periodStart} → {lock.periodEnd}</b><span>{lock.reason}</span></p>)}</div>}{members.length>0&&<div className="saved-controls"><h3>Active team access</h3><p>Members sign in with the exact email shown. Viewers cannot save; operators record work; accountants review and close books.</p>{members.map(member=><p key={member.id}><b>{member.email}</b><span>{member.role} · {member.status}</span></p>)}</div>}</section></>
}
