import {NextResponse} from "next/server";import {z} from "zod";import {getRawDb} from "../../../../db";import {getChatGPTUser} from "../../../company-auth";import {assetAcquisitionEntry,depreciationEntry,rupeesToPaise} from "../../../lib/accounting";import {assertPeriodOpen,prepareJournal} from "../../../lib/book-server";
const acquire=z.object({action:z.literal("acquire"),name:z.string().trim().min(2).max(160),category:z.string().trim().min(2).max(80),acquisitionDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),cost:z.string(),residualValue:z.string().default("0"),usefulLifeMonths:z.number().int().min(1).max(600),paymentAccountCode:z.enum(["1000","1010","2000"]),
 // WDV is the block-of-assets method Section 32 of the Income Tax Act actually requires
 // for most businesses' tax computation — distinct from the SLM the books may use under
 // the Companies Act, which is why both are offered rather than just one.
 depreciationMethod:z.enum(["slm","wdv"]).default("slm"),wdvRateBasisPoints:z.number().int().min(1).max(10000).optional()});
const depreciate=z.object({action:z.literal("depreciate"),assetId:z.string().min(1).max(100),postingDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),months:z.number().int().min(1).max(12)});const schema=z.discriminatedUnion("action",[acquire,depreciate]);
export async function POST(request:Request){const user=await getChatGPTUser(request);if(!user)return NextResponse.json({message:"Please sign in again."},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Check the asset details."},{status:400});const d=parsed.data,raw=getRawDb(),now=Date.now();try{if(d.action==="acquire"){const cost=rupeesToPaise(d.cost),residual=rupeesToPaise(d.residualValue);if(!cost||residual===null||residual>=cost)return NextResponse.json({message:"Residual value must be lower than asset cost."},{status:400});if(d.depreciationMethod==="wdv"&&!d.wdvRateBasisPoints)return NextResponse.json({message:"Enter the WDV rate for this block of assets."},{status:400});await assertPeriodOpen(user.id,d.acquisitionDate);const id=crypto.randomUUID(),journal=await prepareJournal({ownerUserId:user.id,actor:user.email,entryDate:d.acquisitionDate,sourceType:"asset_acquisition",sourceId:id,description:`Asset acquired · ${d.name}`,lines:assetAcquisitionEntry(cost,d.paymentAccountCode)});await raw.batch([raw.prepare("INSERT INTO fixed_assets (id,owner_user_id,name,category,acquisition_date,original_cost_paise,residual_value_paise,useful_life_months,depreciation_method,wdv_rate_basis_points,accumulated_depreciation_paise,payment_account_code,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,user.id,d.name,d.category,d.acquisitionDate,cost,residual,d.usefulLifeMonths,d.depreciationMethod,d.depreciationMethod==="wdv"?d.wdvRateBasisPoints:null,0,d.paymentAccountCode,"active",now,now),...journal.statements]);return NextResponse.json({message:`Asset saved as ${journal.number}.`},{status:201});}
const asset=await raw.prepare("SELECT id,name,original_cost_paise,residual_value_paise,useful_life_months,depreciation_method,wdv_rate_basis_points,accumulated_depreciation_paise FROM fixed_assets WHERE id=? AND owner_user_id=? AND status='active'").bind(d.assetId,user.id).first<{id:string;name:string;original_cost_paise:number;residual_value_paise:number;useful_life_months:number;depreciation_method:string;wdv_rate_basis_points:number|null;accumulated_depreciation_paise:number}>();if(!asset)return NextResponse.json({message:"Asset not found."},{status:404});await assertPeriodOpen(user.id,d.postingDate);
const writtenDownValue=asset.original_cost_paise-asset.accumulated_depreciation_paise;
// WDV depreciates a percentage of whatever the asset is currently worth on the books
// (cost less depreciation already claimed), not a fixed monthly slice of the original
// cost the way SLM does — the charge shrinks every year as the WDV itself shrinks.
const monthly=asset.depreciation_method==="wdv"&&asset.wdv_rate_basis_points
 ?Math.round((writtenDownValue*asset.wdv_rate_basis_points)/10000/12)
 :Math.round((asset.original_cost_paise-asset.residual_value_paise)/asset.useful_life_months);
const available=asset.original_cost_paise-asset.residual_value_paise-asset.accumulated_depreciation_paise,amount=Math.min(available,monthly*d.months);if(amount<=0)return NextResponse.json({message:"This asset is already depreciated to its residual value."},{status:409});const sourceId=`${asset.id}:${d.postingDate}`,prior=await raw.prepare("SELECT id FROM journal_entries WHERE owner_user_id=? AND source_type='asset_depreciation' AND source_id=?").bind(user.id,sourceId).first();if(prior)return NextResponse.json({message:"Depreciation is already posted for this asset and date."},{status:409});const journal=await prepareJournal({ownerUserId:user.id,actor:user.email,entryDate:d.postingDate,sourceType:"asset_depreciation",sourceId,description:`Depreciation · ${asset.name} · ${d.months} month(s)`,lines:depreciationEntry(amount)});await raw.batch([raw.prepare("UPDATE fixed_assets SET accumulated_depreciation_paise=accumulated_depreciation_paise+?,last_depreciation_date=?,updated_at=? WHERE id=? AND owner_user_id=?").bind(amount,d.postingDate,now,asset.id,user.id),...journal.statements]);return NextResponse.json({message:`Depreciation of ₹${(amount/100).toLocaleString("en-IN")} posted as ${journal.number}.`},{status:201});}catch(error){if(error instanceof Error&&error.message==="PERIOD_LOCKED")return NextResponse.json({message:"This accounting period is locked."},{status:409});console.error("Asset posting failed",error);return NextResponse.json({message:"The asset entry could not be posted."},{status:500})}}
