import { ArrowLeftRight, BookOpenCheck, Building2, CircleHelp, FileText, PackagePlus, ReceiptIndianRupee, ShoppingCart, Sparkles, UsersRound } from "lucide-react";
import { chatGPTSignOutPath, requireChatGPTUser } from "../company-auth";
import CommonsAssistant from "../components/commons-assistant";

const steps = [
  { n: "01", title: "Tell Commons who you are", detail: "Add your legal name, GSTIN, address, bank details and invoice prefix. You do this once and can change it later.", href: "/other/business", action: "Set up business", icon: Building2, result: "Your bills use the correct business identity." },
  { n: "02", title: "Add customers and suppliers", detail: "Save the people you sell to and buy from. Nicknames help you group familiar names without changing the legal name.", href: "/customers", action: "Open customers", icon: UsersRound, result: "Every bill, due amount and payment stays linked to the right party." },
  { n: "03", title: "Add what you sell or use", detail: "Create products, services and raw materials. Enter the unit, price, HSN or SAC, GST rate and opening stock.", href: "/products", action: "Open products", icon: PackagePlus, result: "Commons can price bills, watch stock and calculate tax." },
  { n: "04", title: "Record what you buy", detail: "Choose a supplier and enter their invoice. Save as Ordered if goods are on the way; select Receive only after they arrive.", href: "/purchases", action: "Open purchases", icon: ShoppingCart, result: "Received goods update stock, input GST and supplier dues together." },
  { n: "05", title: "Create a customer bill", detail: "Choose the customer and items. Commons checks available stock and calculates CGST + SGST or IGST from the place of supply.", href: "/transactions/new", action: "Create bill", icon: FileText, result: "The invoice, stock movement, customer due and accounts are saved together." },
  { n: "06", title: "Record money received or paid", detail: "Match a receipt to its bill, or use Record Money for expenses and other payments. A bank statement is optional.", href: "/accounts/receipts", action: "Record receipt", icon: ReceiptIndianRupee, result: "Cash or bank and the related customer, supplier or expense balance update." },
  { n: "07", title: "Review before month-end", detail: "Check profit, balance sheet, GST, unmatched bank rows, returns and overdue amounts. Ask your accountant to review, then lock the period.", href: "/accounts", action: "Review accounts", icon: BookOpenCheck, result: "Your books stay balanced, traceable and ready for professional review." },
  { n: "08", title: "Exchange data with TallyPrime", detail: "Download Commons masters first and vouchers second, or upload a Tally voucher XML. Commons previews mappings, duplicates and balance errors before import.", href: "/integrations/tally", action: "Open Tally Sync", icon: ArrowLeftRight, result: "You can work in Commons while your accountant continues in Tally without retyping verified records." },
];

const glossary = [
  ["Money due from customers", "Receivables"], ["Money due to suppliers", "Payables"], ["Stock you currently own", "Inventory"], ["Tax collected on sales", "Output GST"], ["Eligible tax paid on purchases", "Input GST credit"], ["Income minus business costs", "Profit & loss"], ["What the business owns and owes", "Balance sheet"], ["List proving debits equal credits", "Trial balance"], ["Cost of items that were sold", "Cost of goods sold"], ["Two equal effects for every entry", "Double-entry"],
];

export default async function HelpPage() {
  await requireChatGPTUser("/help");
  return <main className="form-shell">
    <header className="site-header workspace-header"><a className="wordmark" href="/" aria-label="Commons home"><CircleHelp/></a><a className="header-action" href={chatGPTSignOutPath("/")}>Sign out</a></header>
    <section className="help-centre">
      <a className="back-link" href="/workspace">← Workspace</a>
      <div className="help-heading"><span>Commons Guide</span><h1>Run the business.<br/>The books follow.</h1><p>You record what happened in familiar words. Commons turns it into stock, tax and accounting records—without asking you to learn bookkeeping first.</p><div><a className="help-primary" href="/settings">Try with demo data</a><a href="#first-week">Your first week</a></div></div>
      <section className="help-principle"><Sparkles/><div><span>The simple rule</span><h2>Start with the real event, not the accounting entry.</h2><p>Sold something? Create a bill. Goods arrived? Receive the purchase. Customer paid? Record the receipt. Commons prepares the linked records and shows the result before anything important is saved.</p></div></section>
      <section className="help-steps">{steps.map(({ n, title, detail, href, action, icon: Icon, result }) => <article key={n}><span>{n}</span><Icon/><div><h2>{title}</h2><p>{detail}</p><small><b>What happens:</b> {result}</small><a href={href}>{action} →</a></div></article>)}</section>
      <section className="help-routine" id="first-week"><div><span>Every day</span><h2>Record the real events</h2><p>Create bills, receive purchases and record money. Deal with low-stock and overdue alerts from the dashboard.</p></div><div><span>Every week</span><h2>Clear the exceptions</h2><p>Review unmatched bank rows, overdue customers, supplier orders and pending salaries. Never approve a match you do not recognise.</p></div><div><span>Every month</span><h2>Close with confidence</h2><p>Review reports and GST working data. Correct mistakes with notes, get accountant approval, back up, then lock the period.</p></div></section>
      <section className="help-safety"><h2>Your first 15-minute setup</h2><div><p><b>1. Select one company</b><span>Check the company name at the top before entering anything. Each company keeps separate customers, stock and books.</span></p><p><b>2. Complete business details</b><span>Add the legal name, state, GSTIN when registered, invoice prefix and bank details.</span></p><p><b>3. Add opening information</b><span>Add customers, suppliers, products and opening balances from the day before you start. Ask your CA if you are unsure.</span></p></div></section>
      <section className="help-routine"><div><span>Purchase</span><h2>Order is not receipt</h2><p>An order changes nothing in stock or accounts. Select Receive only when goods physically arrive and the supplier invoice is known.</p></div><div><span>Sale</span><h2>Bill before collection</h2><p>Create the bill when you sell. Record the receipt later and match it to that bill so the outstanding amount becomes correct.</p></div><div><span>Correction</span><h2>Reverse, do not delete</h2><p>Use sales return, purchase return, credit note or debit note. The original remains visible for audit.</p></div></section>
      <section className="help-safety"><h2>TallyPrime live sync — safe first run</h2><div><p><b>Prepare Tally</b><span>Back up the company, open the correct TallyPrime 7.0 company and enable its HTTP service. Install the Commons connector on the same Windows computer.</span></p><p><b>Pair exactly one company</b><span>In Tally Sync, create a connector key and confirm that the displayed Tally company name and GUID match. Never reuse a pairing for another business.</span></p><p><b>Reconcile before routine use</b><span>Use a test company first. Compare trial balance, party balances, GST and stock after one sale, purchase and receipt. Review every inbound revision or cancellation.</span></p></div></section>
      <section className="help-routine"><div><span>No bank file?</span><h2>Manual entry is allowed</h2><p>Use Record Money or Record Receipt. A statement is helpful for checking, but it is not required to keep books.</p></div><div><span>GST month-end</span><h2>Review, then file</h2><p>Check customer GST status, place of supply, sales tax, purchase documents and GSTR-2B. Commons prepares working data; it does not replace portal verification.</p></div><div><span>Salary</span><h2>Pay and recover clearly</h2><p>Prepare payroll, review deductions and adjust employee advances before marking salary paid.</p></div></section>
      <section className="help-safety"><h2>GST in plain language</h2><div><p><b>Download GSTR-2B as CSV</b><span>On the GST portal, choose the month and download GSTR-2B in CSV format. Open GST in Commons, choose the same month and upload the CSV. Commons compares GSTIN, invoice number and tax; it never changes your books during matching.</span></p><p><b>Understand the four results</b><span>Matched means books and portal agree. Amount difference needs checking. Portal only may mean a purchase is missing. Books only may mean the supplier has not reported it. Do not claim those automatically.</span></p><p><b>Mark special purchases</b><span>Untick ITC eligible when credit is blocked or unavailable. Tick reverse charge only when RCM applies. Commons shows both separately for your accountant to verify.</span></p></div></section>
      <section className="help-routine"><div><span>Long-term items</span><h2>Assets and depreciation</h2><p>Record computers, vehicles and machinery under Fixed Assets, not as an ordinary expense. Enter cost, useful life and residual value; then post depreciation for reviewed months.</p></div><div><span>Year-end</span><h2>Adjust, review, close</h2><p>Your accountant records provisions, doubtful debts and income-tax estimates. After every entry is reviewed, Close Year transfers profit to retained earnings and locks the financial year.</p></div><div><span>Disaster recovery</span><h2>Back up and test</h2><p>Download a backup before month/year close. Verify it in an empty practice company. After restoration, compare trial balance, customer/supplier balances and record counts.</p></div></section>
      <section className="help-accounting"><div className="section-heading"><h2>Plain words → accounting words</h2></div><div>{glossary.map(([plain, term]) => <p key={term}><strong>{plain}</strong><span>{term}</span></p>)}</div></section>
      <section className="help-safety"><h2>Three controls that protect your books</h2><div><p><b>Preview first</b><span>The Copilot prepares the right screen. You confirm every financial save.</span></p><p><b>Correct, never erase</b><span>Use returns, credit notes or debit notes. The original audit trail remains.</span></p><p><b>Close reviewed periods</b><span>After your accountant checks the month, lock it to prevent accidental back-dated changes.</span></p></div></section>
      <section className="help-safety"><h2>Ask Commons Copilot</h2><div><p><b>Try natural language</b><span>Ask “How do I record rent?”, “Create a bill”, “Why is this bank row unmatched?” or “Explain my trial balance.”</span></p><p><b>Connect for open questions</b><span>Go to Settings, enter an OpenAI API key and use Check connection. Built-in workflow questions work even without a key.</span></p><p><b>You stay in control</b><span>Copilot explains and opens prepared workflows. It cannot silently post money, send reminders or file GST.</span></p></div></section>
      <section className="help-accounting"><div className="section-heading"><h2>When something does not look right</h2></div><div><p><strong>Wrong company&apos;s data?</strong><span>Stop, return to Company profiles, select the correct company and reopen the form. Old tabs are blocked from saving.</span></p><p><strong>Tally cannot connect?</strong><span>Keep TallyPrime and the selected company open, confirm the HTTP port, run the connector on that PC and verify the company GUID.</span></p><p><strong>Reports do not agree?</strong><span>Check unreceived orders, unmatched receipts, opening balances, returns and locked dates. Do not post a manual balancing figure without your CA.</span></p><p><strong>Need a clean practice company?</strong><span>Use Settings to populate demo data for that company. Reset removes only Commons-generated demo records.</span></p></div></section>
      <p className="professional-note">Commons prepares management books and GST working data. A qualified chartered accountant should approve statutory filings and final financial statements.</p>
    </section><CommonsAssistant context="dashboard"/>
  </main>;
}
