import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import ts from "typescript";
import { DatabaseSync } from "node:sqlite";
import { z } from "zod";
import { webcrypto } from "node:crypto";
function setup(){
 const db=new DatabaseSync(":memory:");for(const f of fs.readdirSync("drizzle").filter(f=>f.endsWith(".sql")).sort())db.exec(fs.readFileSync("drizzle/"+f,"utf8"));
 const raw={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return /^\s*SELECT/i.test(sql)?{results:db.prepare(sql).all(...args),meta:{changes:0}}:{meta:db.prepare(sql).run(...args)};}};},async batch(statements){db.exec("BEGIN");try{const results=[];for(const statement of statements)results.push(await statement.run());db.exec("COMMIT");return results;}catch(e){db.exec("ROLLBACK");throw e;}}};
 const cache={};function load(file){file=path.resolve(file);if(cache[file])return cache[file];const exports={};cache[file]=exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Error,TextEncoder,TextDecoder,Request,Response,URL,Date,crypto:webcrypto,require(name){if(name==="zod")return {z};if(name==="next/server")return {NextResponse:class extends Response{static json(data,opts){return {data,status:opts?.status||200};}}};if(name.endsWith("/company-auth"))return {getChatGPTUser:async()=>({id:"company-one",email:"test@example.test"})};if(name.endsWith("/db"))return {getRawDb:()=>raw};return load(path.resolve(path.dirname(file),name)+".ts");}});return exports;}
 db.prepare("INSERT INTO products(id,owner_user_id,name,unit,purchase_price_paise,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").run("stock-one","company-one","Sheets","PCS",4000,1,1);
 db.prepare("INSERT INTO products(id,owner_user_id,name,unit,purchase_price_paise,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").run("stock-two","company-two","Sheets","PCS",4000,1,1);
 const engine=load("app/lib/tally-connected-import.ts");return {db,raw,engine,load,async apply(xml,owner="company-one"){const result=await engine.prepareConnectedImport(owner,"accountant",xml);assert.deepEqual(Array.from(result.issues),[]);if(!result.duplicate)await raw.batch(result.statements);return result;}};
}
function invoice({guid="sale",amount=100,qty=1,cancel=false,type="Sales",rev=1}={}){const purchase=type==="Purchase";return `<VOUCHER><GUID>${guid}</GUID><ALTERID>${rev}</ALTERID><DATE>20260909</DATE><VOUCHERTYPENAME>${type}</VOUCHERTYPENAME><VOUCHERNUMBER>${guid}</VOUCHERNUMBER><PARTYLEDGERNAME>Example party</PARTYLEDGERNAME><ISCANCELLED>${cancel?"Yes":"No"}</ISCANCELLED><ALLLEDGERENTRIES.LIST><LEDGERNAME>Example party</LEDGERNAME><AMOUNT>${purchase?amount:-amount}</AMOUNT><BILLALLOCATIONS.LIST><NAME>${guid}</NAME><BILLTYPE>New Ref</BILLTYPE><AMOUNT>${purchase?amount:-amount}</AMOUNT></BILLALLOCATIONS.LIST></ALLLEDGERENTRIES.LIST><ALLLEDGERENTRIES.LIST><LEDGERNAME>${purchase?"Goods purchased":"Sales"}</LEDGERNAME><AMOUNT>${purchase?-amount:amount}</AMOUNT></ALLLEDGERENTRIES.LIST><ALLINVENTORYENTRIES.LIST><STOCKITEMNAME>Sheets</STOCKITEMNAME><ACTUALQTY>${qty} PCS</ACTUALQTY><AMOUNT>${purchase?-amount:amount}</AMOUNT><BATCHALLOCATIONS.LIST><GODOWNNAME>Main</GODOWNNAME><BATCHNAME>Batch-1</BATCHNAME><ACTUALQTY>${qty} PCS</ACTUALQTY><MFDON>20260901</MFDON><EXPIRYPERIOD>20270901</EXPIRYPERIOD></BATCHALLOCATIONS.LIST></ALLINVENTORYENTRIES.LIST></VOUCHER>`;}
const receipt=(amount=40,rev=1)=>`<VOUCHER><GUID>receipt</GUID><ALTERID>${rev}</ALTERID><DATE>20260909</DATE><VOUCHERTYPENAME>Receipt</VOUCHERTYPENAME><VOUCHERNUMBER>Receipt 1</VOUCHERNUMBER><PARTYLEDGERNAME>Example party</PARTYLEDGERNAME><ALLLEDGERENTRIES.LIST><LEDGERNAME>Cash</LEDGERNAME><AMOUNT>-${amount}</AMOUNT></ALLLEDGERENTRIES.LIST><ALLLEDGERENTRIES.LIST><LEDGERNAME>Example party</LEDGERNAME><AMOUNT>${amount}</AMOUNT><BILLALLOCATIONS.LIST><NAME>sale</NAME><BILLTYPE>Agst Ref</BILLTYPE><AMOUNT>${amount}</AMOUNT></BILLALLOCATIONS.LIST></ALLLEDGERENTRIES.LIST></VOUCHER>`;
test("sales import links invoice, stock, batches, party and balanced books once",async()=>{const s=setup();await s.apply(invoice());await s.apply(invoice());assert.equal(s.db.prepare("SELECT COUNT(*) n FROM invoices").get().n,1);assert.equal(s.db.prepare("SELECT total_paise FROM invoices").get().total_paise,10000);assert.equal(s.db.prepare("SELECT SUM(quantity_milli) n FROM stock_movements").get().n,-1000);assert.equal(s.db.prepare("SELECT quantity_milli FROM inventory_batches").get().quantity_milli,-1000);assert.equal(s.db.prepare("SELECT SUM(debit_paise-credit_paise) n FROM journal_lines").get().n,0);});
test("revision reverses original books and stock; cancellation retains history",async()=>{const s=setup();await s.apply(invoice());await s.apply(invoice({amount:200,qty:2,rev:2}));assert.equal(s.db.prepare("SELECT total_paise FROM invoices").get().total_paise,20000);assert.equal(s.db.prepare("SELECT SUM(quantity_milli) n FROM stock_movements").get().n,-2000);await s.apply(invoice({amount:200,qty:2,rev:3,cancel:true}));assert.equal(s.db.prepare("SELECT status FROM invoices").get().status,"cancelled");assert.equal(s.db.prepare("SELECT SUM(quantity_milli) n FROM stock_movements").get().n,0);assert.equal(s.db.prepare("SELECT quantity_milli FROM inventory_batches").get().quantity_milli,0);assert.equal(s.db.prepare("SELECT SUM(debit_paise-credit_paise) n FROM journal_lines WHERE account_code='4000'").get().n,0);assert.equal(s.db.prepare("SELECT COUNT(*) n FROM tally_documents").get().n,3);});
test("receipts update the same customer bill and corrected receipts replace allocation",async()=>{const s=setup();await s.apply(invoice());await s.apply(receipt());assert.equal(s.db.prepare("SELECT paid_paise FROM invoices").get().paid_paise,4000);await s.apply(receipt(60,2));assert.equal(s.db.prepare("SELECT paid_paise FROM invoices").get().paid_paise,6000);const cancel=await s.engine.prepareConnectedImport("company-one","accountant",invoice({cancel:true,rev:2}));assert.ok(cancel.issues.some(i=>i.includes("Reverse related receipts")));});
test("purchases update supplier, purchase lines and stock in isolated company",async()=>{const s=setup();await s.apply(invoice({guid:"buy",type:"Purchase"}));await s.apply(invoice(),"company-two");assert.equal(s.db.prepare("SELECT SUM(quantity_milli) n FROM stock_movements WHERE owner_user_id='company-one'").get().n,1000);assert.equal(s.db.prepare("SELECT COUNT(*) n FROM purchases WHERE owner_user_id='company-one'").get().n,1);});
test("locked periods and unsupported mappings produce no writes",async()=>{const s=setup();s.db.prepare("INSERT INTO period_locks VALUES (?,?,?,?,?,?,?)").run("lock","company-one","2026-09-01","2026-09-30","closed","accountant",1);const result=await s.engine.prepareConnectedImport("company-one","accountant",invoice());assert.ok(result.issues.some(i=>i.includes("locked")));assert.equal(result.statements.length,0);assert.equal(s.db.prepare("SELECT COUNT(*) n FROM invoices").get().n,0);});

test("item-level accounting allocations import once and reject conflicting duplicate totals",async()=>{const s=setup();const direct='<ALLLEDGERENTRIES.LIST><LEDGERNAME>Sales</LEDGERNAME><AMOUNT>100</AMOUNT></ALLLEDGERENTRIES.LIST>';const allocation='<ACCOUNTINGALLOCATIONS.LIST><LEDGERNAME>Sales</LEDGERNAME><AMOUNT>100</AMOUNT></ACCOUNTINGALLOCATIONS.LIST>';const nested=invoice().replace(direct,"").replace('</ALLINVENTORYENTRIES.LIST>',allocation+'</ALLINVENTORYENTRIES.LIST>');await s.apply(nested);assert.equal(s.db.prepare("SELECT SUM(credit_paise) n FROM journal_lines WHERE account_code='4000'").get().n,10000);const bad=invoice({guid:"conflict"}).replace('</ALLINVENTORYENTRIES.LIST>',allocation.replace('100','200')+'</ALLINVENTORYENTRIES.LIST>');await assert.rejects(()=>s.engine.prepareConnectedImport("company-one","accountant",bad),/disagree/);});
test("repeated allocations cannot overpay one bill",async()=>{const s=setup();await s.apply(invoice());const input=receipt(120).replace('<BILLALLOCATIONS.LIST><NAME>sale</NAME><BILLTYPE>Agst Ref</BILLTYPE><AMOUNT>120</AMOUNT></BILLALLOCATIONS.LIST>', '<BILLALLOCATIONS.LIST><NAME>sale</NAME><BILLTYPE>Agst Ref</BILLTYPE><AMOUNT>60</AMOUNT></BILLALLOCATIONS.LIST>'.repeat(2));const result=await s.engine.prepareConnectedImport("company-one","accountant",input);assert.ok(result.issues.some(i=>i.includes("overpay")));assert.equal(result.statements.length,0);});
test("invalid calendar dates, malformed XML and excess precision cannot post",async()=>{const s=setup();for(const input of [invoice().replace('20260909','20260230'),invoice().replace('20260909','20269999'),invoice().replace('<GUID>sale</GUID>','<GUID>sale</BAD>'),invoice().replace('<AMOUNT>100</AMOUNT>','<AMOUNT>100.001</AMOUNT>')])await assert.rejects(()=>s.engine.prepareConnectedImport("company-one","accountant",input));assert.equal(s.db.prepare("SELECT COUNT(*) n FROM journal_entries").get().n,0);});
test("custom account mapping accepts a four-digit code through the import API",async()=>{const s=setup();const route=s.load('app/api/integrations/tally/import/route.ts');const result=await route.POST(new Request('https://commons.test/api/integrations/tally/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'preview',xml:invoice().replace('<LEDGERNAME>Sales</LEDGERNAME>','<LEDGERNAME>Retail revenue</LEDGERNAME>'),mappings:{'retail revenue':'4000'}})}));assert.equal(result.status,200);assert.equal(result.data.ready,1);});
test("inventory in a journal needs explicit mapping instead of becoming stock-in",async()=>{const s=setup();const result=await s.engine.prepareConnectedImport('company-one','accountant',invoice({type:'Journal'}));assert.ok(result.issues.some(i=>i.includes('stock movement mapping')));assert.equal(result.statements.length,0);});
test("escaped angle brackets in ledger names remain intact",async()=>{const s=setup();await s.apply(invoice().replaceAll('Example party','A &lt;B&gt;'));assert.equal(s.db.prepare('SELECT display_name FROM customers').get().display_name,'A <B>');});

test("master exports omit openings by default and preserve receivable/payable signs when requested",async()=>{const s=setup();s.db.prepare("INSERT INTO customers(id,owner_user_id,display_name,primary_phone,opening_balance_paise,balance_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").run('c1','company-one','Debit customer','',10000,'receivable',1,1);s.db.prepare("INSERT INTO customers(id,owner_user_id,display_name,primary_phone,opening_balance_paise,balance_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)").run('c2','company-one','Credit customer','',20000,'payable',1,1);s.db.prepare("INSERT INTO suppliers(id,owner_user_id,name,primary_phone,opening_payable_paise,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").run('s1','company-one','Supplier','',30000,1,1);const route=s.load('app/api/integrations/tally/export/route.ts');const ordinary=await (await route.GET(new Request('https://commons.test/api/integrations/tally/export?scope=masters'))).text();assert.doesNotMatch(ordinary,/<OPENINGBALANCE>-?(100|200|300)\.00</);const included=await (await route.GET(new Request('https://commons.test/api/integrations/tally/export?scope=masters&openings=include'))).text();assert.match(included,/<OPENINGBALANCE>-100\.00</);assert.match(included,/<OPENINGBALANCE>200\.00</);assert.match(included,/<OPENINGBALANCE>300\.00</);});
test("company backup includes Tally history, excludes other companies and supports guarded restore",async()=>{const s=setup();await s.apply(invoice());await s.apply(invoice({guid:'other'}),'company-two');const route=s.load('app/api/accounts/controls/route.ts');const response=await route.GET(new Request('https://commons.test/api/accounts/controls'));assert.equal(response.status,200);const body=await response.json();assert.equal(body.format,'commons-backup-v3');assert.equal(body.restoreSupported,true);assert.equal(body.data.tally_documents.length,1);assert.equal(body.data.tally_documents[0].owner_user_id,'company-one');assert.equal(body.dataSha256.length,64);assert.equal(body.data.tally_bridges,undefined);assert.ok(Array.isArray(body.data.employees));assert.ok(Array.isArray(body.data.purchase_payments));});
test("failed voucher preview retains identity and leaves accounting unchanged",async()=>{
 const s=setup();const route=s.load('app/api/integrations/tally/import/route.ts');
 const xml=invoice({guid:'missing-amount'}).replace('<AMOUNT>-100</AMOUNT>','');
 const response=await route.POST(new Request('https://commons.test/api/integrations/tally/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'preview',xml})}));
 assert.equal(response.data.vouchers[0].date,'2026-09-09');
 assert.equal(response.data.vouchers[0].number,'missing-amount');
 assert.match(response.data.vouchers[0].issues[0],/Required amount/);
 assert.equal(response.data.ready,0);
});
