"use client";
import { companyFetch } from "@/app/company-fetch";
import { todayIST } from "@/app/lib/date";
import { FormEvent, useMemo, useState } from "react";
type Invoice = { id:string; invoiceNumber:string; customerName:string; totalPaise:number; paidPaise:number };
const money=(paise:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(paise/100);
export default function ReceiptForm({invoices}:{invoices:Invoice[]}) {
  const [invoiceId,setInvoiceId]=useState(invoices[0]?.id||""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const selected=useMemo(()=>invoices.find(item=>item.id===invoiceId),[invoices,invoiceId]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setMessage("");const form=new FormData(event.currentTarget);const response=await companyFetch("/api/accounts/receipts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoiceId,paymentDate:form.get("paymentDate"),amount:form.get("amount"),paymentMode:form.get("paymentMode"),reference:form.get("reference")})});const body=await response.json();setBusy(false);if(!response.ok){setError(body.message||"Could not save.");return}setMessage(body.message);setTimeout(()=>location.reload(),700)}
  return <form className="plain-book-form" onSubmit={submit}><div className="form-grid"><label className="span-2"><span>Invoice</span><select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)} required>{invoices.map(item=><option value={item.id} key={item.id}>{item.invoiceNumber} · {item.customerName} · {money(item.totalPaise-item.paidPaise)} due</option>)}</select></label><label><span>Receipt date</span><input type="date" name="paymentDate" defaultValue={todayIST()} required/></label><label><span>Amount received</span><input name="amount" inputMode="decimal" max={selected?(selected.totalPaise-selected.paidPaise)/100:undefined} placeholder="0.00" required/></label><label><span>Received through</span><select name="paymentMode" defaultValue="bank_transfer"><option value="bank_transfer">Bank transfer</option><option value="upi">UPI</option><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="other">Other</option></select></label><label><span>Reference</span><input name="reference" placeholder="UTR, cheque or receipt number"/></label></div>{selected&&<div className="auto-book-preview"><div><strong>{money(selected.totalPaise-selected.paidPaise)} currently due</strong><span>The invoice balance and bank/cash books update together.</span></div></div>}{!invoices.length&&<p className="form-error">No unpaid invoices. Create a bill first.</p>}{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}<button className="submit-button" disabled={busy||!invoices.length}>{busy?"Saving…":"Save receipt"}</button></form>;
}
