"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { FolderOpen,FolderTree,Download,Files,X } from "lucide-react";
import { planFiles,createOrganisedZip,MAX_BYTES,MAX_FILES } from "./organise.mjs";
const size=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
export default function FileOrganiser(){
 const [files,setFiles]=useState<File[]>([]),[mode,setMode]=useState('type'),[keep,setKeep]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');
 const folderInput=useRef<HTMLInputElement>(null),fileInput=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const rows=useMemo(()=>planFiles(files,mode,keep),[files,mode,keep]);
 const filtered=rows.filter(row=>(row.original+' '+row.destination).toLowerCase().includes(search.toLowerCase()));
 const groups=rows.reduce((map,row)=>{map[row.group]=(map[row.group]||0)+1;return map;},{} as Record<string,number>);
 const folderName=files[0]?.webkitRelativePath?.split('/')[0]||'Selected files';
 function choose(list:FileList|null){setError('');setMessage('');if(!list?.length)return;const chosen=Array.from(list);if(chosen.length>MAX_FILES||chosen.reduce((s,f)=>s+f.size,0)>MAX_BYTES){setError('Choose up to 5,000 files and 200 MB. For larger folders, select one subfolder at a time.');return;}setFiles(chosen);setPage(0);setSearch('');}
 function reset(){controller.current?.abort();setFiles([]);setPage(0);setSearch('');setMessage('');setError('');if(folderInput.current)folderInput.current.value='';if(fileInput.current)fileInput.current.value='';}
 async function download(){setBusy(true);setProgress(0);setError('');setMessage('');const abort=new AbortController();controller.current=abort;try{const blob=await createOrganisedZip(rows,{signal:abort.signal,onProgress:(done:number)=>setProgress(done)});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='commons-organised-files.zip';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage('Your organised ZIP is ready. Extract it into a new folder to use the sorted files.');}catch(e){setError(e instanceof Error?e.message:'The ZIP could not be created. Try a smaller folder.');}finally{setBusy(false);controller.current=null;}}
 return <><div className="surface-heading"><span>Other tools</span><h1>File organiser</h1><p>Choose a folder. Preview the order. Download an organised copy.</p></div>
 <div className="organiser-picker"><FolderTree size={36} aria-hidden="true"/><div><h2>{files.length?folderName:'A place for every file'}</h2><p>Files stay on your device. Originals are never moved or deleted.</p></div><div className="organiser-actions"><button type="button" disabled={busy} onClick={()=>folderInput.current?.click()}><FolderOpen size={18}/>Choose folder</button><button type="button" disabled={busy} onClick={()=>fileInput.current?.click()}><Files size={18}/>Choose files</button></div>
 <input hidden type="file" multiple ref={node=>{folderInput.current=node;node?.setAttribute('webkitdirectory','');}} onChange={e=>{choose(e.target.files);e.target.value='';}}/><input hidden type="file" multiple ref={fileInput} onChange={e=>{choose(e.target.files);e.target.value='';}}/>
 <p className="organiser-hint">Up to 5,000 files · 200 MB per download. On phones, use Choose files if folder selection is unavailable.</p></div>
 <div className="organiser-controls"><label>Organise by<select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setPage(0);setMessage('');}}><option value="type">File type · Documents, Images, Videos…</option><option value="extension">Extension · PDF, JPG, XLSX…</option><option value="month">Last modified month · UTC</option></select></label><label className="organiser-check"><input type="checkbox" disabled={busy} checked={keep} onChange={e=>{setKeep(e.target.checked);setPage(0);setMessage('');}}/>Keep original subfolders within each group</label></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}
 {!!files.length&&<><div className="organiser-summary"><strong>{files.length.toLocaleString()} files</strong><span>{size(files.reduce((n,f)=>n+f.size,0))}</span><span>{Object.keys(groups).length} output folders</span><button disabled={busy} onClick={reset}><X size={16}/>Clear selection</button></div><div className="organiser-groups">{Object.entries(groups).map(([name,count])=><span key={name}>{name} <b>{count}</b></span>)}</div>
 <div className="organiser-preview-heading"><h2>Preview</h2><label><span className="sr-only">Search file paths</span><input placeholder="Search files or folders" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div><p className="organiser-hint">Matching names are numbered automatically. All {files.length} files will be included in the ZIP, including files hidden by this search.</p>
 <div className="organiser-table"><table><thead><tr><th>Original path</th><th>Organised path</th><th>Size</th></tr></thead><tbody>{filtered.slice(page*100,page*100+100).map(row=><tr key={row.index}><td>{row.original}</td><td>{row.destination}{row.renamed&&<small>Renamed to avoid a conflict or unsupported characters</small>}</td><td>{size(row.file.size)}</td></tr>)}</tbody></table>{!filtered.length&&<p>No matching files.</p>}</div>
 <div className="organiser-pagination"><span>{filtered.length?`${page*100+1}–${Math.min((page+1)*100,filtered.length)} of ${filtered.length}`:'0 files'}</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*100>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>
 <div className="organiser-download" aria-busy={busy}>{busy?<><label>Preparing {progress} of {files.length} files<progress max={files.length} value={progress}/></label><button onClick={()=>controller.current?.abort()}>Cancel</button></>:<button className="submit-button" onClick={download}><Download size={18}/>Download organised ZIP</button>}</div></>}
 {!files.length&&<p className="organiser-empty">Your folder preview will appear here. Sorting uses file names, extensions and modified dates; file contents are not analysed.</p>}
 </>;
}
