"use client";
import { useState } from "react";
import { companyFetch } from "@/app/company-fetch";
import type { TallyDocument } from "../../lib/tally-document";
export default function DocumentHistory({documents}:{documents:{id:string;kind:string;created_at:number;revision:string}[]}){
 const [selected,setSelected]=useState<TallyDocument|null>(null);const [error,setError]=useState("");
 async function open(id:string){try{const response=await companyFetch(`/api/integrations/tally/bridge?document=${encodeURIComponent(id)}`);const body=await response.json();if(!response.ok)throw Error(body.message);setSelected(body.document);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load document.");}}
 return <section><h3>Synchronised documents & revision history</h3>{error&&<p role="alert">{error}</p>}{!documents.length&&<p>No connected documents imported yet.</p>}{documents.map(d=><button key={d.id} style={{margin:"4px"}} onClick={()=>open(d.id)}>{d.kind} · {new Date(d.created_at).toLocaleString()}</button>)}{selected&&<div className="bridge-review"><button onClick={()=>setSelected(null)}>Close details</button><h3>{selected.type} · {selected.number}</h3><p>{selected.partyName} · {selected.date} · {selected.cancelled?"Cancelled":"Posted"}</p><p>GSTIN: {selected.gstin||"Not supplied"} · Place of supply: {selected.placeOfSupply||"Not supplied"}</p>{selected.items.map((item,index)=><article key={index}><strong>{item.name}</strong><p>{Math.abs(item.milli)/1000} {item.unit} · ₹{(Math.abs(item.amount)/100).toLocaleString("en-IN")} · HSN {item.hsn||"Not supplied"}</p>{item.batches.map((batch,i)=><p key={i}>{batch.warehouse} / {batch.name} · {Math.abs(batch.milli)/1000} {batch.unit} · Expiry {batch.expiry||"Not supplied"}</p>)}</article>)}<h4>Bill allocations</h4>{selected.ledgers.flatMap(l=>l.bills.map((bill,i)=><p key={l.name+i}>{l.name} · {bill.reference} · {bill.type} · ₹{(Math.abs(bill.amount)/100).toLocaleString("en-IN")}</p>))}<h4>E-document references received from Tally</h4><p>IRN: {selected.gst.irn||"Not supplied"}</p><p>Acknowledgement: {selected.gst.ackNumber||"Not supplied"} · {selected.gst.ackDate}</p><p>E-way bill: {selected.gst.ewayBill||"Not supplied"}</p><p className="tally-note">These are received references. Commons has not generated or validated an IRN, submitted an e-way bill, or filed a GST return.</p></div>}</section>;
}
